
application:
  graceful_shutdown_timeout:

grpc_server:
  auth_address: "authservice:50051"
  user_address: "0.0.0.0:50052"

mysql:
  port: 3306
  host: app-database
  db_name: app_db
  username: app
  password: app0lk2o20


logger:
  development: true
  service_name: "user_service"
  file_path: "./logs/service.log"
