
application:
  graceful_shutdown_timeout:

grpc_server:
  auth_address: "127.0.0.1:50051"
  user_address: "127.0.0.1:50052"

mysql:
  port: 3311
  host: localhost
  db_name: user_db
  username: user
  password: usert0lk2o20


logger:
  development: true
  service_name: "user_service"
  file_path: "./logs/service.log"
