package errmsg

const (
	ErrorMsgNotFound                          = "record not found"
	ErrorMsgCantScanQueryResult               = "can't scan query result"
	ErrorMsgSomethingWentWrong                = "something went wrong"
	ErrorMsgPhoneNumberIsNotUnique            = "phone number is not unique"
	ErrorMsgInvalidInput                      = "invalid input"
	ErrorMsgPhoneNumberIsNotValid             = "phone number is not valid"
	ErrorMsgUserNotAllowed                    = "user not allowed"
	ErrorMsgCategoryIsNotValid                = "category is not valid"
	ErrorMsgUserNameOrPasswordNotCorrect      = "username or password isn't correct"
	ErrorMsgProductNotFound                   = "ProductNotFound"
	ErrorMsgTokenIsRequired                   = "token is required"
	ErrorMsgTokenIsNotValid                   = "token is not valid"
	ErrorMsgFailedToMarshalEvent              = "failed to marshal event"
	ErrorMsgCouldntAddToCart                  = "Couldn’t add to cart."
	ErrorMsgFailedToPublishOrderCheckoutEvent = "failed to publish order checkout event"
	ErrorMsgFinalizingPurchase                = "Error finalizing purchase"
	ErrorMsgCartNotFound                      = "cart is not found"
	ErrorMsgInvalidQty                        = "invalid quantity"
	ErrorMsgCartIsEmpty                       = "cart is empty"
	ErrorMsgFailedToHashPassword              = "failed to hash password"
	ErrorMsgInvalidPassword                   = "invalid password"
	ErrorMsgYouAreNotAuthorizedToCreateAStore = "you are not authorized to create a store"
	ErrorMsgFailedToListStoreIDs              = "failed to list store IDs"
	ErrorMsgFailedToCachedStore               = "failed to fetch cached stores"
	ErrorMsgFailedToFetchFreshStoreFromDB     = "failed to fetch fresh stores from DB"
	ErrorMsgFailedToCreateStoreInDB           = "failed to create store in DB"
	ErrorMsgFailedToDeleteStoreInDB           = "failed to delete store in DB"
	ErrorMsgFailedToUpdateStoreInDB           = "failed to update store in DB"
	ErrorMsgStoreNotFound                     = "store not found"
	ErrorMsgFailedToDeleteStore               = "failed to delete store "
	ErrorMsgFailedToGetStoreInDB              = "failed to get store in DB"
	ErrorMsgFailedToCreateProductInDB         = "failed to create product in DB"
	ErrorMsgSkuAlreadyExists                  = "sku already exists"
	ErrorMsgFailedToGetProductInDB            = "failed to get product in DB"
	ErrorMsgFailedToGetCartInDB               = "failed to get cart in DB"
	ErrorMsgSKUIsNotValid                     = "sku is not valid"
	ErrorMsgImageURLIsNotValid                = "image url is not valid"
)
