services:
  user-database:
    image: mysql:8.0
    ports:
      - "3311:3306"
    container_name: user-database
    volumes:
      - userdbdata:/var/lib/mysql
    restart: always
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_ROOT_PASSWORD: Mp13831383
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: usert0lk2o20

  product-database:
    image: mysql:8.0
    ports:
      - "3310:3306"
    container_name: product-database
    volumes:
      - productdbdata:/var/lib/mysql
    restart: always
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_ROOT_PASSWORD: Mp13831383
      MYSQL_DATABASE: product_db
      MYSQL_USER: product
      MYSQL_PASSWORD: productt0lk2o20
  store-database:
    image: mysql:8.0
    ports:
      - "3312:3306"
    container_name: store-database
    volumes:
      - storedbdata:/var/lib/mysql
    restart: always
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_ROOT_PASSWORD: Mp13831383
      MYSQL_DATABASE: store_db
      MYSQL_USER: store
      MYSQL_PASSWORD: storet0lk2o20

volumes:
  userdbdata:
  productdbdata:
  storedbdata:
