application:
  graceful_shutdown_timeout:


grpc_client:
  auth_address: "authservice:50051"
  user_address: "userservice:50052"
  store_address: "storeservice:50053"
  product_address: "productservice:50054"
  cart_address: "cartservice:50060"

http_server:
  address: "0.0.0.0:8080"


logger:
  development: true
  service_name: "gateway"
  file_path: "./logs/gateway.log"