application:
  graceful_shutdown_timeout:

grpc_server:
  product_address: "127.0.0.1:50054"


mysql:
  port: 3310
  host: localhost
  db_name: product_db
  username: product
  password: productt0lk2o20