application:
  graceful_shutdown_timeout:

grpc_server:
  product_address: "127.0.0.1:50054"


mysql:
  port: 3310
  host: localhost
  db_name: product_db
  username: product
  password: productt0lk2o20

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  product_ttl_minutes: 10