application:
  graceful_shutdown_timeout:

grpc_server:
  store_address: "127.0.0.1:50053"

mysql:
  port: 3312
  host: localhost
  db_name: store_db
  username: store
  password: storet0lk2o20


redis:
  host: localhost
  port: 6379
  password: ""
  db: 1
  product_ttl_minutes: 10