application:
  graceful_shutdown_timeout:

grpc_server:
  store_address: "0.0.0.0:50053"

mysql:
  port: 3306
  host: app-database
  db_name: app_db
  username: app
  password: app0lk2o20



redis:
  host: redis
  port: 6379
  password: ""
  db: 1
  store_ttl_minutes: 10

logger:
  development: true
  service_name: "store_service"
  file_path: "./logs/store.log"

metrics:
  Port: 9100
