
auth:
  sign_key: jwt_secret
  refresh_expiration_time: "168h"
  access_expiration_time: "24h"
  access_subject: "ac"
  refresh_subject: "rt"

http_server:
  port: 8082



mysql:
  port: 3312
  host: localhost
  db_name: store_db
  username: store
  password: storet0lk2o20